from __future__ import annotations

from typing_extensions import NotRequired, TypedDict

from ..core import UNSET, Optional, OptionalNullable, SdkBaseModel
from .enums.all_vaults import AllVaultsOrStr
from .enums.card_type import CardTypeOrStr
from .enums.payment_type import PaymentTypeOrStr
from .unions.expiration_month2 import ExpirationMonth2, ExpirationMonth2Dict
from .unions.expiration_year2 import ExpirationYear2, ExpirationYear2Dict


class PaymentProfileAttributes(SdkBaseModel):
    """alias to credit_card_attributes"""

    chargify_token: Optional[str] = UNSET
    """(Optional) Token received after sending billing information using Maxio.js (formerly Chargify.js). This token
    must be passed as a sole attribute of ``payment_profile_attributes`` (e.g., tok_9g6hw85pnpt6knmskpwp4ttt)."""

    id: Optional[int] = UNSET
    payment_type: Optional[PaymentTypeOrStr] = UNSET
    first_name: Optional[str] = UNSET
    """(Optional) First name on card or bank account. If omitted, the first_name from customer attributes will be
    used."""

    last_name: Optional[str] = UNSET
    """(Optional) Last name on card or bank account. If omitted, the last_name from customer attributes will be used."""

    masked_card_number: Optional[str] = UNSET
    full_number: Optional[str] = UNSET
    """The full credit card number (string representation, e.g., 5424000000000015)"""

    card_type: Optional[CardTypeOrStr] = UNSET
    """(Optional, used only for Subscription Import) If you know the card type (e.g., Visa, MC, etc.) you may supply it
    here so that we may display the card type in the UI."""

    expiration_month: Optional[ExpirationMonth2] = UNSET
    """(Optional when performing a Subscription Import via vault_token, required otherwise) The 1- or 2-digit credit
    card expiration month, as an integer or string, e.g., 5"""

    expiration_year: Optional[ExpirationYear2] = UNSET
    """(Optional when performing a Subscription Import via vault_token, required otherwise) The 4-digit credit card
    expiration year, as an integer or string, e.g., 2012"""

    billing_address: Optional[str] = UNSET
    """(Optional, may be required by your product configuration or gateway settings) The credit card or bank account
    billing street address (e.g., 123 Main St.). This value is merely passed through to the payment gateway."""

    billing_address_2: OptionalNullable[str] = UNSET
    """(Optional) Second line of the customer’s billing address, e.g., Apt. 100"""

    billing_city: Optional[str] = UNSET
    """(Optional, may be required by your product configuration or gateway settings) The credit card or bank account
    billing address city (e.g., “Boston”). This value is merely passed through to the payment gateway."""

    billing_state: Optional[str] = UNSET
    """(Optional, may be required by your product configuration or gateway settings) The credit card or bank account
    billing address state (e.g., MA). This value is merely passed through to the payment gateway. This must conform to
    the `ISO_3166-1 <https://en.wikipedia.org/wiki/ISO_3166-1#Current_codes>`__ in order to be valid for tax locale
    purposes."""

    billing_country: Optional[str] = UNSET
    """(Optional, may be required by your product configuration or gateway settings) The credit card or bank account
    billing address country, required in `ISO_3166-1 alpha-2 <https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2>`__
    format (e.g., “US”). This value is merely passed through to the payment gateway. Some gateways require country codes
    in a specific format. Check your gateway’s documentation. If creating an ACH subscription, only US is supported at
    this time."""

    billing_zip: Optional[str] = UNSET
    """(Optional, may be required by your product configuration or gateway settings) The credit card or bank account
    billing address zip code (e.g., 12345). This value is merely passed through to the payment gateway."""

    current_vault: Optional[AllVaultsOrStr] = UNSET
    """(Optional, used only for Subscription Import) The vault that stores the payment profile with the provided
    vault_token."""

    vault_token: Optional[str] = UNSET
    """(Optional, used only for Subscription Import) The “token” provided by your vault storage for an already stored
    payment profile"""

    customer_vault_token: Optional[str] = UNSET
    """(Optional, used only for Subscription Import) (only for Authorize.Net CIM storage or Square) The
    customerProfileId for the owner of the customerPaymentProfileId provided as the vault_token"""

    customer_id: Optional[int] = UNSET
    paypal_email: Optional[str] = UNSET
    payment_method_nonce: Optional[str] = UNSET
    """(Required for Square unless importing with vault_token and customer_vault_token) The nonce generated by the
    Square Javascript library (SqPaymentForm)"""

    gateway_handle: Optional[str] = UNSET
    """(Optional) This attribute is only available if MultiGateway feature is enabled for your Site. This feature is in
    the Private Beta currently. gateway_handle is used to directly select a gateway where a payment profile will be
    stored in. Every connected gateway must have a unique gateway handle specified. Read `Multigateway description
    <https://chargify.zendesk.com/hc/en-us/articles/4407761759643#connecting-with-multiple-gateways>`__ to learn more
    about new concepts that MultiGateway introduces and the default behavior when this attribute is not passed."""

    cvv: Optional[str] = UNSET
    """(Optional, may be required by your gateway settings) The 3- or 4-digit Card Verification Value. This value is
    merely passed through to the payment gateway."""

    last_four: Optional[str] = UNSET
    """(Optional, used only for Subscription Import) If you have the last 4 digits of the credit card number, you may
    supply them here so that we may create a masked card number (e.g., XXXX-XXXX-XXXX-1234) for display in the UI. Last
    4 digits are required for refunds in Auth.Net."""


class PaymentProfileAttributesDict(TypedDict):
    chargify_token: NotRequired[str]
    id: NotRequired[int]
    payment_type: NotRequired[PaymentTypeOrStr]
    first_name: NotRequired[str]
    last_name: NotRequired[str]
    masked_card_number: NotRequired[str]
    full_number: NotRequired[str]
    card_type: NotRequired[CardTypeOrStr]
    expiration_month: NotRequired[ExpirationMonth2Dict]
    expiration_year: NotRequired[ExpirationYear2Dict]
    billing_address: NotRequired[str]
    billing_address_2: NotRequired[str | None]
    billing_city: NotRequired[str]
    billing_state: NotRequired[str]
    billing_country: NotRequired[str]
    billing_zip: NotRequired[str]
    current_vault: NotRequired[AllVaultsOrStr]
    vault_token: NotRequired[str]
    customer_vault_token: NotRequired[str]
    customer_id: NotRequired[int]
    paypal_email: NotRequired[str]
    payment_method_nonce: NotRequired[str]
    gateway_handle: NotRequired[str]
    cvv: NotRequired[str]
    last_four: NotRequired[str]
