from enum import Enum
from typing import Annotated, TypeAlias

from ...core import open_enum_validator


class EventKey(str, Enum):
    PAYMENT_SUCCESS = "payment_success"
    PAYMENT_FAILURE = "payment_failure"
    SIGNUP_SUCCESS = "signup_success"
    SIGNUP_FAILURE = "signup_failure"
    DELAYED_SIGNUP_CREATION_SUCCESS = "delayed_signup_creation_success"
    DELAYED_SIGNUP_CREATION_FAILURE = "delayed_signup_creation_failure"
    BILLING_DATE_CHANGE = "billing_date_change"
    EXPIRATION_DATE_CHANGE = "expiration_date_change"
    RENEWAL_SUCCESS = "renewal_success"
    RENEWAL_FAILURE = "renewal_failure"
    SUBSCRIPTION_STATE_CHANGE = "subscription_state_change"
    SUBSCRIPTION_PRODUCT_CHANGE = "subscription_product_change"
    SUBSCRIPTION_PRODUCT_CHANGE_SCHEDULED = "subscription_product_change_scheduled"
    PENDING_CANCELLATION_CHANGE = "pending_cancellation_change"
    EXPIRING_CARD = "expiring_card"
    CUSTOMER_UPDATE = "customer_update"
    CUSTOMER_CREATE = "customer_create"
    CUSTOMER_DELETE = "customer_delete"
    COMPONENT_ALLOCATION_CHANGE = "component_allocation_change"
    METERED_USAGE = "metered_usage"
    PREPAID_USAGE = "prepaid_usage"
    UPGRADE_DOWNGRADE_SUCCESS = "upgrade_downgrade_success"
    UPGRADE_DOWNGRADE_FAILURE = "upgrade_downgrade_failure"
    STATEMENT_CLOSED = "statement_closed"
    STATEMENT_SETTLED = "statement_settled"
    SUBSCRIPTION_CARD_UPDATE = "subscription_card_update"
    SUBSCRIPTION_GROUP_CARD_UPDATE = "subscription_group_card_update"
    SUBSCRIPTION_BANK_ACCOUNT_UPDATE = "subscription_bank_account_update"
    REFUND_SUCCESS = "refund_success"
    REFUND_FAILURE = "refund_failure"
    UPCOMING_RENEWAL_NOTICE = "upcoming_renewal_notice"
    TRIAL_END_NOTICE = "trial_end_notice"
    DUNNING_STEP_REACHED = "dunning_step_reached"
    INVOICE_ISSUED = "invoice_issued"
    INVOICE_PENDING = "invoice_pending"
    PREPAID_SUBSCRIPTION_BALANCE_CHANGED = "prepaid_subscription_balance_changed"
    SUBSCRIPTION_GROUP_SIGNUP_SUCCESS = "subscription_group_signup_success"
    SUBSCRIPTION_GROUP_SIGNUP_FAILURE = "subscription_group_signup_failure"
    DIRECT_DEBIT_PAYMENT_PAID_OUT = "direct_debit_payment_paid_out"
    DIRECT_DEBIT_PAYMENT_REJECTED = "direct_debit_payment_rejected"
    DIRECT_DEBIT_PAYMENT_PENDING = "direct_debit_payment_pending"
    PENDING_PAYMENT_CREATED = "pending_payment_created"
    PENDING_PAYMENT_FAILED = "pending_payment_failed"
    PENDING_PAYMENT_COMPLETED = "pending_payment_completed"
    PROFORMA_INVOICE_ISSUED = "proforma_invoice_issued"
    SUBSCRIPTION_PREPAYMENT_ACCOUNT_BALANCE_CHANGED = "subscription_prepayment_account_balance_changed"
    SUBSCRIPTION_SERVICE_CREDIT_ACCOUNT_BALANCE_CHANGED = "subscription_service_credit_account_balance_changed"
    CUSTOM_FIELD_VALUE_CHANGE = "custom_field_value_change"
    ITEM_PRICE_POINT_CHANGED = "item_price_point_changed"
    RENEWAL_SUCCESS_RECREATED = "renewal_success_recreated"
    RENEWAL_FAILURE_RECREATED = "renewal_failure_recreated"
    PAYMENT_SUCCESS_RECREATED = "payment_success_recreated"
    PAYMENT_FAILURE_RECREATED = "payment_failure_recreated"
    SUBSCRIPTION_DELETION = "subscription_deletion"
    SUBSCRIPTION_GROUP_BANK_ACCOUNT_UPDATE = "subscription_group_bank_account_update"
    SUBSCRIPTION_PAYPAL_ACCOUNT_UPDATE = "subscription_paypal_account_update"
    SUBSCRIPTION_GROUP_PAYPAL_ACCOUNT_UPDATE = "subscription_group_paypal_account_update"
    SUBSCRIPTION_CUSTOMER_CHANGE = "subscription_customer_change"
    ACCOUNT_TRANSACTION_CHANGED = "account_transaction_changed"
    GO_CARDLESS_PAYMENT_PAID_OUT = "go_cardless_payment_paid_out"
    GO_CARDLESS_PAYMENT_REJECTED = "go_cardless_payment_rejected"
    GO_CARDLESS_PAYMENT_PENDING = "go_cardless_payment_pending"
    STRIPE_DIRECT_DEBIT_PAYMENT_PAID_OUT = "stripe_direct_debit_payment_paid_out"
    STRIPE_DIRECT_DEBIT_PAYMENT_REJECTED = "stripe_direct_debit_payment_rejected"
    STRIPE_DIRECT_DEBIT_PAYMENT_PENDING = "stripe_direct_debit_payment_pending"
    MAXIO_PAYMENTS_DIRECT_DEBIT_PAYMENT_PAID_OUT = "maxio_payments_direct_debit_payment_paid_out"
    MAXIO_PAYMENTS_DIRECT_DEBIT_PAYMENT_REJECTED = "maxio_payments_direct_debit_payment_rejected"
    MAXIO_PAYMENTS_DIRECT_DEBIT_PAYMENT_PENDING = "maxio_payments_direct_debit_payment_pending"
    INVOICE_IN_COLLECTIONS_CANCELED = "invoice_in_collections_canceled"
    SUBSCRIPTION_ADDED_TO_GROUP = "subscription_added_to_group"
    SUBSCRIPTION_REMOVED_FROM_GROUP = "subscription_removed_from_group"
    CHARGEBACK_OPENED = "chargeback_opened"
    CHARGEBACK_LOST = "chargeback_lost"
    CHARGEBACK_ACCEPTED = "chargeback_accepted"
    CHARGEBACK_CLOSED = "chargeback_closed"
    CHARGEBACK_WON = "chargeback_won"
    PAYMENT_COLLECTION_METHOD_CHANGED = "payment_collection_method_changed"
    COMPONENT_BILLING_DATE_CHANGED = "component_billing_date_changed"
    CHJS_TOKENIZATION_FAILURE = "chjs_tokenization_failure"
    CHJS_TOKENIZATION_SUCCESS = "chjs_tokenization_success"
    SUBSCRIPTION_TERM_RENEWAL_SCHEDULED = "subscription_term_renewal_scheduled"
    SUBSCRIPTION_TERM_RENEWAL_PENDING = "subscription_term_renewal_pending"
    SUBSCRIPTION_TERM_RENEWAL_ACTIVATED = "subscription_term_renewal_activated"
    SUBSCRIPTION_TERM_RENEWAL_REMOVED = "subscription_term_renewal_removed"

    __str__ = str.__str__


EventKeyOrStr: TypeAlias = Annotated[EventKey | str, open_enum_validator(EventKey)]
